class Panic : RuntimeException {
  override
  public constructor initialize(message: string) {
    this.message = message;
  }
}

fn panic(message: string) -> void {
  throw new Panic("panic");
}

fn assert(expression: boolean, message: string) -> void {
  if (!expression) {
    panic(message);
  }
}

fn test_assert(expression: boolean) -> void {
  assert(expression, "test failed");
}
